<?php

namespace Modules\Core\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Core\app\Models\Country;

class CountriesSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $countries = [
      ['id' => '1', 'name' => ['ar' => 'اندورا', 'fr' => 'Andorre', 'en' => 'Andorra'], 'code' => 'ad'],
      [
        'id' => '2',
        'name' => [
          'ar' => 'الامارات العربية المتحدة',
          'fr' => 'Emirats Arabes Unis',
          'en' => 'United Arab Emirates',
        ],
        'code' => 'ae',
      ],
      [
        'id' => '3',
        'name' => ['ar' => 'افغانستان', 'fr' => 'L\'Afghanistan', 'en' => 'Afghanistan'],
        'code' => 'af',
      ],
      [
        'id' => '4',
        'name' => ['ar' => 'انتيغوا وبربودا', 'fr' => 'Antigua-et-Barbuda', 'en' => 'Antigua and Barbuda'],
        'code' => 'ag',
      ],
      ['id' => '5', 'name' => ['ar' => 'انغيلا', 'fr' => 'Anguilla', 'en' => 'Anguilla'], 'code' => 'ai'],
      ['id' => '6', 'name' => ['ar' => 'البانيا', 'fr' => 'Albanie', 'en' => 'Albania'], 'code' => 'al'],
      ['id' => '7', 'name' => ['ar' => 'ارمينيا', 'fr' => 'Arménie', 'en' => 'Armenia'], 'code' => 'am'],
      [
        'id' => '8',
        'name' => [
          'ar' => 'جزر الانتيل الهولندية',
          'fr' => 'Antilles néerlandaises',
          'en' => 'Netherlands Antilles',
        ],
        'code' => 'an',
      ],
      ['id' => '9', 'name' => ['ar' => 'انغولا', 'fr' => 'Angola', 'en' => 'Angola'], 'code' => 'ao'],
      ['id' => '10', 'name' => ['ar' => 'الارجنتين', 'fr' => 'Argentine', 'en' => 'Argentina'], 'code' => 'ar'],
      ['id' => '11', 'name' => ['ar' => 'النمسا', 'fr' => 'L\'Autriche', 'en' => 'Austria'], 'code' => 'at'],
      ['id' => '12', 'name' => ['ar' => 'استراليا', 'fr' => 'Australie', 'en' => 'Australia'], 'code' => 'au'],
      ['id' => '13', 'name' => ['ar' => 'اروبا', 'fr' => 'Aruba', 'en' => 'Aruba'], 'code' => 'aw'],
      ['id' => '14', 'name' => ['ar' => 'اذربيجان', 'fr' => 'Azerbaïdjan', 'en' => 'Azerbaijan'], 'code' => 'az'],
      [
        'id' => '15',
        'name' => ['ar' => 'البوسنة والهرسك', 'fr' => 'Bosnie Herzégovine', 'en' => 'Bosnia and Herzegovina'],
        'code' => 'ba',
      ],
      ['id' => '16', 'name' => ['ar' => 'بربادوس', 'fr' => 'La Barbade', 'en' => 'Barbados'], 'code' => 'bb'],
      ['id' => '17', 'name' => ['ar' => 'بنغلاديش', 'fr' => 'Bangladesh', 'en' => 'Bangladesh'], 'code' => 'bd'],
      ['id' => '18', 'name' => ['ar' => 'بلجيكا', 'fr' => 'Belgique', 'en' => 'Belgium'], 'code' => 'be'],
      [
        'id' => '19',
        'name' => ['ar' => 'بوركينا فاسو', 'fr' => 'Burkina Faso', 'en' => 'Burkina Faso'],
        'code' => 'bf',
      ],
      ['id' => '20', 'name' => ['ar' => 'بلغاريا', 'fr' => 'Bulgarie', 'en' => 'Bulgaria'], 'code' => 'bg'],
      ['id' => '21', 'name' => ['ar' => 'البحرين', 'fr' => 'Bahreïn', 'en' => 'Bahrain'], 'code' => 'bh'],
      ['id' => '22', 'name' => ['ar' => 'بوروندي', 'fr' => 'Burundi', 'en' => 'Burundi'], 'code' => 'bi'],
      ['id' => '23', 'name' => ['ar' => 'بنين', 'fr' => 'Bénin', 'en' => 'Benin'], 'code' => 'bj'],
      ['id' => '24', 'name' => ['ar' => 'برمودا', 'fr' => 'Bermudes', 'en' => 'Bermuda'], 'code' => 'bm'],
      [
        'id' => '25',
        'name' => ['ar' => 'بروناي دار السلام', 'fr' => 'Brunei Darussalam', 'en' => 'Brunei Darussalam'],
        'code' => 'bn',
      ],
      ['id' => '26', 'name' => ['ar' => 'بوليفيا', 'fr' => 'Bolivie', 'en' => 'Bolivia'], 'code' => 'bo'],
      ['id' => '27', 'name' => ['ar' => 'البرازيل', 'fr' => 'Brésil', 'en' => 'Brazil'], 'code' => 'br'],
      ['id' => '28', 'name' => ['ar' => 'الباهاما', 'fr' => 'Bahamas', 'en' => 'Bahamas'], 'code' => 'bs'],
      ['id' => '29', 'name' => ['ar' => 'بوتان', 'fr' => 'Bhoutan', 'en' => 'Bhutan'], 'code' => 'bt'],
      ['id' => '30', 'name' => ['ar' => 'بوتسوانا', 'fr' => 'Botswana', 'en' => 'Botswana'], 'code' => 'bw'],
      [
        'id' => '31',
        'name' => ['ar' => 'روسيا البيضاء', 'fr' => 'Biélorussie', 'en' => 'Belarus'],
        'code' => 'by',
      ],
      ['id' => '32', 'name' => ['ar' => 'بليز', 'fr' => 'Belize', 'en' => 'Belize'], 'code' => 'bz'],
      ['id' => '33', 'name' => ['ar' => 'كندا', 'fr' => 'Canada', 'en' => 'Canada'], 'code' => 'ca'],
      [
        'id' => '34',
        'name' => [
          'ar' => 'جزر كوكوس (كيلينغ)',
          'fr' => 'Îles Cocos (Keeling)',
          'en' => 'Cocos (Keeling) Islands',
        ],
        'code' => 'cc',
      ],
      [
        'id' => '35',
        'name' => [
          'ar' => 'جمهورية الكونغو الديموقراطية',
          'fr' => 'République Démocratique du Congo',
          'en' => 'Democratic Republic of the Congo',
        ],
        'code' => 'cd',
      ],
      [
        'id' => '36',
        'name' => [
          'ar' => 'جمهورية افريقيا الوسطى',
          'fr' => 'République centrafricaine',
          'en' => 'Central African Republic',
        ],
        'code' => 'cf',
      ],
      ['id' => '37', 'name' => ['ar' => 'الكونغو', 'fr' => 'Congo', 'en' => 'Congo'], 'code' => 'cg'],
      ['id' => '38', 'name' => ['ar' => 'سويسرا', 'fr' => 'Suisse', 'en' => 'Switzerland'], 'code' => 'ch'],
      [
        'id' => '39',
        'name' => [
          'ar' => 'ساحل العاج (ساحل العاج)',
          'fr' => 'Cote D\'Ivoire (Côte d\'Ivoire)',
          'en' => 'Cote D\'Ivoire (Ivory Coast)',
        ],
        'code' => 'ci',
      ],
      [
        'id' => '40',
        'name' => ['ar' => 'جزر كوك', 'fr' => 'les Îles Cook', 'en' => 'Cook Islands'],
        'code' => 'ck',
      ],
      ['id' => '41', 'name' => ['ar' => 'تشيلي', 'fr' => 'Chili', 'en' => 'Chile'], 'code' => 'cl'],
      ['id' => '42', 'name' => ['ar' => 'الكاميرون', 'fr' => 'Cameroun', 'en' => 'Cameroon'], 'code' => 'cm'],
      ['id' => '43', 'name' => ['ar' => 'الصين', 'fr' => 'Chine', 'en' => 'China'], 'code' => 'cn'],
      ['id' => '44', 'name' => ['ar' => 'كولومبيا', 'fr' => 'Colombie', 'en' => 'Colombia'], 'code' => 'co'],
      [
        'id' => '45',
        'name' => ['ar' => 'كوستا ريكا', 'fr' => 'Costa Rica', 'en' => 'Costa Rica'],
        'code' => 'cr',
      ],
      ['id' => '46', 'name' => ['ar' => 'كوبا', 'fr' => 'Cuba', 'en' => 'Cuba'], 'code' => 'cu'],
      [
        'id' => '47',
        'name' => ['ar' => 'الراس الاخضر', 'fr' => 'Cap-Vert', 'en' => 'Cape Verde'],
        'code' => 'cv',
      ],
      [
        'id' => '48',
        'name' => ['ar' => 'جزيرة الكريسماس', 'fr' => 'L\'île de noël', 'en' => 'Christmas Island'],
        'code' => 'cx',
      ],
      ['id' => '49', 'name' => ['ar' => 'قبرص', 'fr' => 'Chypre', 'en' => 'Cyprus'], 'code' => 'cy'],
      [
        'id' => '50',
        'name' => ['ar' => 'جمهورية التشيك', 'fr' => 'République Tchèque', 'en' => 'Czech Republic'],
        'code' => 'cz',
      ],
      ['id' => '51', 'name' => ['ar' => 'المانيا', 'fr' => 'Allemagne', 'en' => 'Germany'], 'code' => 'de'],
      ['id' => '52', 'name' => ['ar' => 'جيبوتي', 'fr' => 'Djibouti', 'en' => 'Djibouti'], 'code' => 'dj'],
      ['id' => '53', 'name' => ['ar' => 'الدنمارك', 'fr' => 'Danemark', 'en' => 'Denmark'], 'code' => 'dk'],
      ['id' => '54', 'name' => ['ar' => 'دومينيكا', 'fr' => 'Dominique', 'en' => 'Dominica'], 'code' => 'dm'],
      [
        'id' => '55',
        'name' => [
          'ar' => 'جمهورية الدومنيكان',
          'fr' => 'République Dominicaine',
          'en' => 'Dominican Republic',
        ],
        'code' => 'do',
      ],
      ['id' => '56', 'name' => ['ar' => 'الجزائر', 'fr' => 'Algérie', 'en' => 'Algeria'], 'code' => 'dz'],
      ['id' => '57', 'name' => ['ar' => 'الاكوادور', 'fr' => 'L\'Équateur', 'en' => 'Ecuador'], 'code' => 'ec'],
      ['id' => '58', 'name' => ['ar' => 'استونيا', 'fr' => 'Estonie', 'en' => 'Estonia'], 'code' => 'ee'],
      ['id' => '59', 'name' => ['ar' => 'مصر', 'fr' => 'Egypte', 'en' => 'Egypt'], 'code' => 'eg'],
      [
        'id' => '60',
        'name' => ['ar' => 'الصحراء الغربية', 'fr' => 'Sahara occidental', 'en' => 'Western Sahara'],
        'code' => 'eh',
      ],
      ['id' => '61', 'name' => ['ar' => 'اريتريا', 'fr' => 'Erythrée', 'en' => 'Eritrea'], 'code' => 'er'],
      ['id' => '62', 'name' => ['ar' => 'اسبانيا', 'fr' => 'Espagne', 'en' => 'Spain'], 'code' => 'es'],
      ['id' => '63', 'name' => ['ar' => 'اثيوبيا', 'fr' => 'Ethiopie', 'en' => 'Ethiopia'], 'code' => 'et'],
      ['id' => '64', 'name' => ['ar' => 'فنلندا', 'fr' => 'Finlande', 'en' => 'Finland'], 'code' => 'fi'],
      ['id' => '65', 'name' => ['ar' => 'فيجي', 'fr' => 'Fidji', 'en' => 'Fiji'], 'code' => 'fj'],
      [
        'id' => '66',
        'name' => [
          'ar' => 'جزر فوكلاند (مالفيناس)',
          'fr' => 'Iles Malouines (Malouines)',
          'en' => 'Falkland Islands (Malvinas)',
        ],
        'code' => 'fk',
      ],
      [
        'id' => '67',
        'name' => [
          'ar' => 'ولايات ميكرونيزيا الموحدة',
          'fr' => 'États fédérés de Micronésie',
          'en' => 'Federated States of Micronesia',
        ],
        'code' => 'fm',
      ],
      [
        'id' => '68',
        'name' => ['ar' => 'جزر صناعية', 'fr' => 'Îles Féroé', 'en' => 'Faroe Islands'],
        'code' => 'fo',
      ],
      ['id' => '69', 'name' => ['ar' => 'فرنسا', 'fr' => 'France', 'en' => 'France'], 'code' => 'fr'],
      ['id' => '70', 'name' => ['ar' => 'الغابون', 'fr' => 'Gabon', 'en' => 'Gabon'], 'code' => 'ga'],
      [
        'id' => '71',
        'name' => [
          'ar' => 'بريطانيا العظمى (المملكة المتحدة)',
          'fr' => 'Grande-Bretagne (UK)',
          'en' => 'Great Britain (UK)',
        ],
        'code' => 'gb',
      ],
      ['id' => '72', 'name' => ['ar' => 'غرينادا', 'fr' => 'Grenade', 'en' => 'Grenada'], 'code' => 'gd'],
      ['id' => '73', 'name' => ['ar' => 'جورجيا', 'fr' => 'Géorgie', 'en' => 'Georgia'], 'code' => 'ge'],
      [
        'id' => '74',
        'name' => ['ar' => 'غيانا الفرنسية', 'fr' => 'Guinée Française', 'en' => 'French Guiana'],
        'code' => 'gf',
      ],
      ['id' => '75', 'name' => ['ar' => 'لا شيء', 'fr' => 'NUL', 'en' => 'NULL'], 'code' => 'gg'],
      ['id' => '76', 'name' => ['ar' => 'غانا', 'fr' => 'Ghana', 'en' => 'Ghana'], 'code' => 'gh'],
      ['id' => '77', 'name' => ['ar' => 'جبل طارق', 'fr' => 'Gibraltar', 'en' => 'Gibraltar'], 'code' => 'gi'],
      [
        'id' => '78',
        'name' => ['ar' => 'الارض الخضراء', 'fr' => 'Groenland', 'en' => 'Greenland'],
        'code' => 'gl',
      ],
      ['id' => '79', 'name' => ['ar' => 'غامبيا', 'fr' => 'Gambie', 'en' => 'Gambia'], 'code' => 'gm'],
      ['id' => '80', 'name' => ['ar' => 'غينيا', 'fr' => 'Guinée', 'en' => 'Guinea'], 'code' => 'gn'],
      [
        'id' => '81',
        'name' => ['ar' => 'جوادلوب', 'fr' => 'La guadeloupe', 'en' => 'Guadeloupe'],
        'code' => 'gp',
      ],
      [
        'id' => '82',
        'name' => ['ar' => 'غينيا الاستوائية', 'fr' => 'Guinée Équatoriale', 'en' => 'Equatorial Guinea'],
        'code' => 'gq',
      ],
      ['id' => '83', 'name' => ['ar' => 'اليونان', 'fr' => 'Grèce', 'en' => 'Greece'], 'code' => 'gr'],
      [
        'id' => '84',
        'name' => [
          'ar' => 'جورجيا وجزر ساندويتش',
          'fr' => 'Géorgie du Sud et les îles Sandwich du Sud',
          'en' => 'S. Georgia and S. Sandwich Islands',
        ],
        'code' => 'gs',
      ],
      ['id' => '85', 'name' => ['ar' => 'غواتيمالا', 'fr' => 'Guatemala', 'en' => 'Guatemala'], 'code' => 'gt'],
      [
        'id' => '86',
        'name' => ['ar' => 'غينيا بيساو', 'fr' => 'Guinée-Bissau', 'en' => 'Guinea-Bissau'],
        'code' => 'gw',
      ],
      ['id' => '87', 'name' => ['ar' => 'غيانا', 'fr' => 'Guyane', 'en' => 'Guyana'], 'code' => 'gy'],
      ['id' => '88', 'name' => ['ar' => 'هونغ كونغ', 'fr' => 'Hong Kong', 'en' => 'Hong Kong'], 'code' => 'hk'],
      ['id' => '89', 'name' => ['ar' => 'هندوراس', 'fr' => 'Honduras', 'en' => 'Honduras'], 'code' => 'hn'],
      [
        'id' => '90',
        'name' => ['ar' => 'كرواتيا (هرفاتسكا)', 'fr' => 'Croatie (Hrvatska)', 'en' => 'Croatia (Hrvatska)'],
        'code' => 'hr',
      ],
      ['id' => '91', 'name' => ['ar' => 'هايتي', 'fr' => 'Haïti', 'en' => 'Haiti'], 'code' => 'ht'],
      ['id' => '92', 'name' => ['ar' => 'اليونان', 'fr' => 'Hongrie', 'en' => 'Hungary'], 'code' => 'hu'],
      ['id' => '93', 'name' => ['ar' => 'اندونيسيا', 'fr' => 'Indonésie', 'en' => 'Indonesia'], 'code' => 'id'],
      ['id' => '94', 'name' => ['ar' => 'ايرلندا', 'fr' => 'Irlande', 'en' => 'Ireland'], 'code' => 'ie'],
      ['id' => '96', 'name' => ['ar' => 'الهند', 'fr' => 'Inde', 'en' => 'India'], 'code' => 'in'],
      ['id' => '97', 'name' => ['ar' => 'العراق', 'fr' => 'Irak', 'en' => 'Iraq'], 'code' => 'iq'],
      ['id' => '98', 'name' => ['ar' => 'ايران', 'fr' => 'Iran', 'en' => 'Iran'], 'code' => 'ir'],
      ['id' => '99', 'name' => ['ar' => 'ايسلندا', 'fr' => 'Islande', 'en' => 'Iceland'], 'code' => 'is'],
      ['id' => '100', 'name' => ['ar' => 'ايطاليا', 'fr' => 'Italie', 'en' => 'Italy'], 'code' => 'it'],
      ['id' => '101', 'name' => ['ar' => 'جامايكا', 'fr' => 'Jamaïque', 'en' => 'Jamaica'], 'code' => 'jm'],
      ['id' => '102', 'name' => ['ar' => 'الاردن', 'fr' => 'Jordan', 'en' => 'Jordan'], 'code' => 'jo'],
      ['id' => '103', 'name' => ['ar' => 'اليابان', 'fr' => 'Japon', 'en' => 'Japan'], 'code' => 'jp'],
      ['id' => '104', 'name' => ['ar' => 'كينيا', 'fr' => 'Kenya', 'en' => 'Kenya'], 'code' => 'ke'],
      [
        'id' => '105',
        'name' => ['ar' => 'قرغيزستان', 'fr' => 'Kirghizistan', 'en' => 'Kyrgyzstan'],
        'code' => 'kg',
      ],
      ['id' => '106', 'name' => ['ar' => 'كمبوديا', 'fr' => 'Cambodge', 'en' => 'Cambodia'], 'code' => 'kh'],
      ['id' => '107', 'name' => ['ar' => 'كيريباس', 'fr' => 'Kiribati', 'en' => 'Kiribati'], 'code' => 'ki'],
      ['id' => '108', 'name' => ['ar' => 'جزر القمر', 'fr' => 'Comores', 'en' => 'Comoros'], 'code' => 'km'],
      [
        'id' => '109',
        'name' => [
          'ar' => 'سانت كيتس ونيفيس',
          'fr' => 'Saint-Christophe-et-Niévès',
          'en' => 'Saint Kitts and Nevis',
        ],
        'code' => 'kn',
      ],
      [
        'id' => '110',
        'name' => ['ar' => 'كوريا الشمالية', 'fr' => 'Corée du Nord', 'en' => 'Korea (North)'],
        'code' => 'kp',
      ],
      [
        'id' => '111',
        'name' => ['ar' => 'كوريا، جنوب)', 'fr' => 'COREE DU SUD)', 'en' => 'Korea (South)'],
        'code' => 'kr',
      ],
      ['id' => '112', 'name' => ['ar' => 'الكويت', 'fr' => 'Koweit', 'en' => 'Kuwait'], 'code' => 'kw'],
      [
        'id' => '113',
        'name' => ['ar' => 'جزر كايمان', 'fr' => 'Îles Caïmans', 'en' => 'Cayman Islands'],
        'code' => 'ky',
      ],
      [
        'id' => '114',
        'name' => ['ar' => 'كازاخستان', 'fr' => 'Le kazakhstan', 'en' => 'Kazakhstan'],
        'code' => 'kz',
      ],
      ['id' => '115', 'name' => ['ar' => 'لاوس', 'fr' => 'Laos', 'en' => 'Laos'], 'code' => 'la'],
      ['id' => '116', 'name' => ['ar' => 'لبنان', 'fr' => 'Liban', 'en' => 'Lebanon'], 'code' => 'lb'],
      [
        'id' => '117',
        'name' => ['ar' => 'القديسة لوسيا', 'fr' => 'Sainte-Lucie', 'en' => 'Saint Lucia'],
        'code' => 'lc',
      ],
      [
        'id' => '118',
        'name' => ['ar' => 'ليختنشتاين', 'fr' => 'Le Liechtenstein', 'en' => 'Liechtenstein'],
        'code' => 'li',
      ],
      ['id' => '119', 'name' => ['ar' => 'سيريلانكا', 'fr' => 'Sri Lanka', 'en' => 'Sri Lanka'], 'code' => 'lk'],
      ['id' => '120', 'name' => ['ar' => 'ليبيريا', 'fr' => 'Libéria', 'en' => 'Liberia'], 'code' => 'lr'],
      ['id' => '121', 'name' => ['ar' => 'ليسوتو', 'fr' => 'Lesotho', 'en' => 'Lesotho'], 'code' => 'ls'],
      ['id' => '122', 'name' => ['ar' => 'ليتوانيا', 'fr' => 'Lituanie', 'en' => 'Lithuania'], 'code' => 'lt'],
      [
        'id' => '123',
        'name' => ['ar' => 'لوكسمبورغ', 'fr' => 'Luxembourg', 'en' => 'Luxembourg'],
        'code' => 'lu',
      ],
      ['id' => '124', 'name' => ['ar' => 'لاتفيا', 'fr' => 'Lettonie', 'en' => 'Latvia'], 'code' => 'lv'],
      ['id' => '125', 'name' => ['ar' => 'ليبيا', 'fr' => 'Libye', 'en' => 'Libya'], 'code' => 'ly'],
      ['id' => '126', 'name' => ['ar' => 'المغرب', 'fr' => 'Maroc', 'en' => 'Morocco'], 'code' => 'ma'],
      ['id' => '127', 'name' => ['ar' => 'موناكو', 'fr' => 'Monaco', 'en' => 'Monaco'], 'code' => 'mc'],
      ['id' => '128', 'name' => ['ar' => 'مولدوفا', 'fr' => 'La Moldavie', 'en' => 'Moldova'], 'code' => 'md'],
      ['id' => '129', 'name' => ['ar' => 'مدغشقر', 'fr' => 'Madagascar', 'en' => 'Madagascar'], 'code' => 'mg'],
      [
        'id' => '130',
        'name' => ['ar' => 'جزر مارشال', 'fr' => 'Iles Marshall', 'en' => 'Marshall Islands'],
        'code' => 'mh',
      ],
      ['id' => '131', 'name' => ['ar' => 'مقدونيا', 'fr' => 'Macédoine', 'en' => 'Macedonia'], 'code' => 'mk'],
      ['id' => '132', 'name' => ['ar' => 'مالي', 'fr' => 'Mali', 'en' => 'Mali'], 'code' => 'ml'],
      ['id' => '133', 'name' => ['ar' => 'ميانمار', 'fr' => 'Myanmar', 'en' => 'Myanmar'], 'code' => 'mm'],
      ['id' => '134', 'name' => ['ar' => 'منغوليا', 'fr' => 'Mongolie', 'en' => 'Mongolia'], 'code' => 'mn'],
      ['id' => '135', 'name' => ['ar' => 'ماكاو', 'fr' => 'Macao', 'en' => 'Macao'], 'code' => 'mo'],
      [
        'id' => '136',
        'name' => [
          'ar' => 'جزر مريانا الشمالية',
          'fr' => 'Îles Mariannes du Nord',
          'en' => 'Northern Mariana Islands',
        ],
        'code' => 'mp',
      ],
      ['id' => '137', 'name' => ['ar' => 'مارتينيك', 'fr' => 'Martinique', 'en' => 'Martinique'], 'code' => 'mq'],
      [
        'id' => '138',
        'name' => ['ar' => 'موريتانيا', 'fr' => 'Mauritanie', 'en' => 'Mauritania'],
        'code' => 'mr',
      ],
      [
        'id' => '139',
        'name' => ['ar' => 'مونتسيرات', 'fr' => 'Montserrat', 'en' => 'Montserrat'],
        'code' => 'ms',
      ],
      ['id' => '140', 'name' => ['ar' => 'مالطا', 'fr' => 'Malte', 'en' => 'Malta'], 'code' => 'mt'],
      ['id' => '141', 'name' => ['ar' => 'موريشيوس', 'fr' => 'Maurice', 'en' => 'Mauritius'], 'code' => 'mu'],
      ['id' => '142', 'name' => ['ar' => 'جزر المالديف', 'fr' => 'Maldives', 'en' => 'Maldives'], 'code' => 'mv'],
      ['id' => '143', 'name' => ['ar' => 'مالاوي', 'fr' => 'Malawi', 'en' => 'Malawi'], 'code' => 'mw'],
      ['id' => '144', 'name' => ['ar' => 'المكسيك', 'fr' => 'Mexique', 'en' => 'Mexico'], 'code' => 'mx'],
      ['id' => '145', 'name' => ['ar' => 'ماليزيا', 'fr' => 'Malaisie', 'en' => 'Malaysia'], 'code' => 'my'],
      ['id' => '146', 'name' => ['ar' => 'موزمبيق', 'fr' => 'Mozambique', 'en' => 'Mozambique'], 'code' => 'mz'],
      ['id' => '147', 'name' => ['ar' => 'ناميبيا', 'fr' => 'Namibie', 'en' => 'Namibia'], 'code' => 'na'],
      [
        'id' => '148',
        'name' => ['ar' => 'كاليدونيا الجديدة', 'fr' => 'Nouvelle Calédonie', 'en' => 'New Caledonia'],
        'code' => 'nc',
      ],
      ['id' => '149', 'name' => ['ar' => 'النيجر', 'fr' => 'Niger', 'en' => 'Niger'], 'code' => 'ne'],
      [
        'id' => '150',
        'name' => ['ar' => 'جزيرة نورفولك', 'fr' => 'l\'ile de Norfolk', 'en' => 'Norfolk Island'],
        'code' => 'nf',
      ],
      ['id' => '151', 'name' => ['ar' => 'نيجيريا', 'fr' => 'Nigeria', 'en' => 'Nigeria'], 'code' => 'ng'],
      ['id' => '152', 'name' => ['ar' => 'نيكاراغوا', 'fr' => 'Nicaragua', 'en' => 'Nicaragua'], 'code' => 'ni'],
      ['id' => '153', 'name' => ['ar' => 'هولندا', 'fr' => 'Pays-Bas', 'en' => 'Netherlands'], 'code' => 'nl'],
      ['id' => '154', 'name' => ['ar' => 'النرويج', 'fr' => 'Norvège', 'en' => 'Norway'], 'code' => 'no'],
      ['id' => '155', 'name' => ['ar' => 'نيبال', 'fr' => 'Népal', 'en' => 'Nepal'], 'code' => 'np'],
      ['id' => '156', 'name' => ['ar' => 'ناورو', 'fr' => 'Nauru', 'en' => 'Nauru'], 'code' => 'nr'],
      ['id' => '157', 'name' => ['ar' => 'نيوي', 'fr' => 'Niue', 'en' => 'Niue'], 'code' => 'nu'],
      [
        'id' => '158',
        'name' => [
          'ar' => 'نيوزيلندا (اوتياروا)',
          'fr' => 'Nouvelle-Zélande (Aotearoa)',
          'en' => 'New Zealand (Aotearoa)',
        ],
        'code' => 'nz',
      ],
      ['id' => '159', 'name' => ['ar' => 'سلطنة عمان', 'fr' => 'Oman', 'en' => 'Oman'], 'code' => 'om'],
      ['id' => '160', 'name' => ['ar' => 'بناما', 'fr' => 'Panama', 'en' => 'Panama'], 'code' => 'pa'],
      ['id' => '161', 'name' => ['ar' => 'بيرو', 'fr' => 'Pérou', 'en' => 'Peru'], 'code' => 'pe'],
      [
        'id' => '162',
        'name' => ['ar' => 'بولينيزيا الفرنسية', 'fr' => 'Polynésie française', 'en' => 'French Polynesia'],
        'code' => 'pf',
      ],
      [
        'id' => '163',
        'name' => [
          'ar' => 'بابوا غينيا الجديدة',
          'fr' => 'Papouasie Nouvelle Guinée',
          'en' => 'Papua New Guinea',
        ],
        'code' => 'pg',
      ],
      [
        'id' => '164',
        'name' => ['ar' => 'الفلبين', 'fr' => 'Philippines', 'en' => 'Philippines'],
        'code' => 'ph',
      ],
      ['id' => '165', 'name' => ['ar' => 'باكستان', 'fr' => 'Pakistan', 'en' => 'Pakistan'], 'code' => 'pk'],
      ['id' => '166', 'name' => ['ar' => 'بولندا', 'fr' => 'Pologne', 'en' => 'Poland'], 'code' => 'pl'],
      [
        'id' => '167',
        'name' => [
          'ar' => 'سانت بيير وميكلون',
          'fr' => 'Saint Pierre et Miquelon',
          'en' => 'Saint Pierre and Miquelon',
        ],
        'code' => 'pm',
      ],
      ['id' => '168', 'name' => ['ar' => 'بيتكيرن', 'fr' => 'Pitcairn', 'en' => 'Pitcairn'], 'code' => 'pn'],
      [
        'id' => '169',
        'name' => [
          'ar' => 'الاراضي الفلسطينية',
          'fr' => 'Territoire Palestinien',
          'en' => 'Palestinian Territory',
        ],
        'code' => 'ps',
      ],
      ['id' => '170', 'name' => ['ar' => 'البرتغال', 'fr' => 'le Portugal', 'en' => 'Portugal'], 'code' => 'pt'],
      ['id' => '171', 'name' => ['ar' => 'بالاو', 'fr' => 'Palau', 'en' => 'Palau'], 'code' => 'pw'],
      ['id' => '172', 'name' => ['ar' => 'باراغواي', 'fr' => 'Paraguay', 'en' => 'Paraguay'], 'code' => 'py'],
      ['id' => '173', 'name' => ['ar' => 'دولة قطر', 'fr' => 'Qatar', 'en' => 'Qatar'], 'code' => 'qa'],
      ['id' => '174', 'name' => ['ar' => 'جمع شمل', 'fr' => 'Réunion', 'en' => 'Reunion'], 'code' => 're'],
      ['id' => '175', 'name' => ['ar' => 'رومانيا', 'fr' => 'Roumanie', 'en' => 'Romania'], 'code' => 'ro'],
      [
        'id' => '176',
        'name' => ['ar' => 'الاتحاد الروسي', 'fr' => 'Fédération Russe', 'en' => 'Russian Federation'],
        'code' => 'ru',
      ],
      ['id' => '177', 'name' => ['ar' => 'رواندا', 'fr' => 'Rwanda', 'en' => 'Rwanda'], 'code' => 'rw'],
      [
        'id' => '178',
        'name' => ['ar' => 'المملكة العربية السعودية', 'fr' => 'Arabie Saoudite', 'en' => 'Saudi Arabia'],
        'code' => 'sa',
      ],
      [
        'id' => '179',
        'name' => ['ar' => 'جزر سليمان', 'fr' => 'Les îles Salomon', 'en' => 'Solomon Islands'],
        'code' => 'sb',
      ],
      [
        'id' => '180',
        'name' => ['ar' => 'سيشيل', 'fr' => 'les Seychelles', 'en' => 'Seychelles'],
        'code' => 'sc',
      ],
      ['id' => '181', 'name' => ['ar' => 'سودان', 'fr' => 'Soudan', 'en' => 'Sudan'], 'code' => 'sd'],
      ['id' => '182', 'name' => ['ar' => 'السويد', 'fr' => 'Suède', 'en' => 'Sweden'], 'code' => 'se'],
      ['id' => '183', 'name' => ['ar' => 'سنغافورة', 'fr' => 'Singapour', 'en' => 'Singapore'], 'code' => 'sg'],
      [
        'id' => '184',
        'name' => ['ar' => 'سانت هيلانة', 'fr' => 'Sainte Hélène', 'en' => 'Saint Helena'],
        'code' => 'sh',
      ],
      ['id' => '185', 'name' => ['ar' => 'سلوفينيا', 'fr' => 'La slovénie', 'en' => 'Slovenia'], 'code' => 'si'],
      [
        'id' => '186',
        'name' => [
          'ar' => 'سفالبارد وجان مايان',
          'fr' => 'Svalbard et Jan Mayen',
          'en' => 'Svalbard and Jan Mayen',
        ],
        'code' => 'sj',
      ],
      ['id' => '187', 'name' => ['ar' => 'سلوفاكيا', 'fr' => 'La slovaquie', 'en' => 'Slovakia'], 'code' => 'sk'],
      [
        'id' => '188',
        'name' => ['ar' => 'سيرا ليون', 'fr' => 'Sierra Leone', 'en' => 'Sierra Leone'],
        'code' => 'sl',
      ],
      [
        'id' => '189',
        'name' => ['ar' => 'سان مارينو', 'fr' => 'Saint Marin', 'en' => 'San Marino'],
        'code' => 'sm',
      ],
      ['id' => '190', 'name' => ['ar' => 'السنغال', 'fr' => 'Sénégal', 'en' => 'Senegal'], 'code' => 'sn'],
      ['id' => '191', 'name' => ['ar' => 'الصومال', 'fr' => 'Somalie', 'en' => 'Somalia'], 'code' => 'so'],
      ['id' => '192', 'name' => ['ar' => 'سورينام', 'fr' => 'Suriname', 'en' => 'Suriname'], 'code' => 'sr'],
      [
        'id' => '193',
        'name' => [
          'ar' => 'ساو تومي وبرنسيبي',
          'fr' => 'Sao Tomé et Principe',
          'en' => 'Sao Tome and Principe',
        ],
        'code' => 'st',
      ],
      [
        'id' => '194',
        'name' => ['ar' => 'السلفادور', 'fr' => 'Le Salvador', 'en' => 'El Salvador'],
        'code' => 'sv',
      ],
      ['id' => '195', 'name' => ['ar' => 'سوريا', 'fr' => 'Syrie', 'en' => 'Syria'], 'code' => 'sy'],
      ['id' => '196', 'name' => ['ar' => 'سوازيلاند', 'fr' => 'Swaziland', 'en' => 'Swaziland'], 'code' => 'sz'],
      [
        'id' => '197',
        'name' => [
          'ar' => 'جزر تركس وكايكوس',
          'fr' => 'îles Turques-et-Caïques',
          'en' => 'Turks and Caicos Islands',
        ],
        'code' => 'tc',
      ],
      ['id' => '198', 'name' => ['ar' => 'تشاد', 'fr' => 'Le tchad', 'en' => 'Chad'], 'code' => 'td'],
      [
        'id' => '199',
        'name' => [
          'ar' => 'المناطق الجنوبية لفرنسا',
          'fr' => 'Terres australes françaises',
          'en' => 'French Southern Territories',
        ],
        'code' => 'tf',
      ],
      ['id' => '200', 'name' => ['ar' => 'ليذهب', 'fr' => 'Aller', 'en' => 'Togo'], 'code' => 'tg'],
      ['id' => '201', 'name' => ['ar' => 'تايلاند', 'fr' => 'Thaïlande', 'en' => 'Thailand'], 'code' => 'th'],
      [
        'id' => '202',
        'name' => ['ar' => 'طاجيكستان', 'fr' => 'Tadjikistan', 'en' => 'Tajikistan'],
        'code' => 'tj',
      ],
      ['id' => '203', 'name' => ['ar' => 'توكيلاو', 'fr' => 'Tokelau', 'en' => 'Tokelau'], 'code' => 'tk'],
      [
        'id' => '204',
        'name' => ['ar' => 'تركمانستان', 'fr' => 'Turkménistan', 'en' => 'Turkmenistan'],
        'code' => 'tm',
      ],
      ['id' => '205', 'name' => ['ar' => 'تونس', 'fr' => 'Tunisie', 'en' => 'Tunisia'], 'code' => 'tn'],
      ['id' => '206', 'name' => ['ar' => 'تونغا', 'fr' => 'Tonga', 'en' => 'Tonga'], 'code' => 'to'],
      ['id' => '207', 'name' => ['ar' => 'تركيا', 'fr' => 'dinde', 'en' => 'Turkey'], 'code' => 'tr'],
      [
        'id' => '208',
        'name' => ['ar' => 'ترينداد وتوباغو', 'fr' => 'Trinité-et-Tobago', 'en' => 'Trinidad and Tobago'],
        'code' => 'tt',
      ],
      ['id' => '209', 'name' => ['ar' => 'توفالو', 'fr' => 'Tuvalu', 'en' => 'Tuvalu'], 'code' => 'tv'],
      ['id' => '210', 'name' => ['ar' => 'تايوان', 'fr' => 'Taïwan', 'en' => 'Taiwan'], 'code' => 'tw'],
      ['id' => '211', 'name' => ['ar' => 'تنزانيا', 'fr' => 'Tanzanie', 'en' => 'Tanzania'], 'code' => 'tz'],
      ['id' => '212', 'name' => ['ar' => 'اوكرانيا', 'fr' => 'Ukraine', 'en' => 'Ukraine'], 'code' => 'ua'],
      ['id' => '213', 'name' => ['ar' => 'اوغندا', 'fr' => 'Ouganda', 'en' => 'Uganda'], 'code' => 'ug'],
      ['id' => '214', 'name' => ['ar' => 'اوروغواي', 'fr' => 'Uruguay', 'en' => 'Uruguay'], 'code' => 'uy'],
      [
        'id' => '215',
        'name' => ['ar' => 'اوزبكستان', 'fr' => 'Ouzbékistan', 'en' => 'Uzbekistan'],
        'code' => 'uz',
      ],
      [
        'id' => '216',
        'name' => [
          'ar' => 'سانت فنسنت وجزر غرينادين',
          'fr' => 'Saint-Vincent-et-les-Grenadines',
          'en' => 'Saint Vincent and the Grenadines',
        ],
        'code' => 'vc',
      ],
      ['id' => '217', 'name' => ['ar' => 'فنزويلا', 'fr' => 'Venezuela', 'en' => 'Venezuela'], 'code' => 've'],
      [
        'id' => '218',
        'name' => [
          'ar' => 'جزر العذراء البريطانية)',
          'fr' => 'Îles vierges britanniques',
          'en' => 'Virgin Islands (British)',
        ],
        'code' => 'vg',
      ],
      [
        'id' => '219',
        'name' => [
          'ar' => 'جزر فيرجن (الولايات المتحدة)',
          'fr' => 'Îles Vierges (États-Unis)',
          'en' => 'Virgin Islands (U.S.)',
        ],
        'code' => 'vi',
      ],
      ['id' => '220', 'name' => ['ar' => 'فيتنام', 'fr' => 'Viet Nam', 'en' => 'Viet Nam'], 'code' => 'vn'],
      ['id' => '221', 'name' => ['ar' => 'فانواتو', 'fr' => 'Vanuatu', 'en' => 'Vanuatu'], 'code' => 'vu'],
      [
        'id' => '222',
        'name' => ['ar' => 'واليس وفوتونا', 'fr' => 'Wallis et Futuna', 'en' => 'Wallis and Futuna'],
        'code' => 'wf',
      ],
      ['id' => '223', 'name' => ['ar' => 'ساموا', 'fr' => 'Samoa', 'en' => 'Samoa'], 'code' => 'ws'],
      ['id' => '224', 'name' => ['ar' => 'اليمن', 'fr' => 'Yémen', 'en' => 'Yemen'], 'code' => 'ye'],
      ['id' => '225', 'name' => ['ar' => 'مايوت', 'fr' => 'Mayotte', 'en' => 'Mayotte'], 'code' => 'yt'],
      [
        'id' => '226',
        'name' => ['ar' => 'جنوب افريقيا', 'fr' => 'Afrique du Sud', 'en' => 'South Africa'],
        'code' => 'za',
      ],
      ['id' => '227', 'name' => ['ar' => 'زامبيا', 'fr' => 'Zambie', 'en' => 'Zambia'], 'code' => 'zm'],
      [
        'id' => '228',
        'name' => ['ar' => 'زائير (سابقة)', 'fr' => 'Zaïre (ancien)', 'en' => 'Zaire (former)'],
        'code' => 'zr',
      ],
      ['id' => '229', 'name' => ['ar' => 'زيمبابوي', 'fr' => 'Zimbabwe', 'en' => 'Zimbabwe'], 'code' => 'zw'],
      [
        'id' => '230',
        'name' => [
          'ar' => 'الولايات المتحدة',
          'fr' => 'les États-Unis d\'Amérique',
          'en' => 'United States of America',
        ],
        'code' => 'us',
      ],
    ];
    foreach ($countries as $item) {
      Country::query()->updateOrCreate([
        'code' => $item['code'],
        'name' => $item['name'],
      ]);
    }
  }
}
