<?php

// Variables
return [
    "creatorName" => "Codliy",
    "creatorUrl" => "https://codliy.com",
    "templateName" => "Codliy",
    "templateSuffix" => "Codliy - Software Studio",
    "templateVersion" => "1.0.0",
    "templateFree" => false,
    "templateDescription" => "Codliy — a software studio building web, mobile, cloud, AI and UI/UX products.",
    "templateKeyword" => "Codliy, software development, web development, mobile apps, cloud, AI, UI UX",
    "licenseUrl" => "https://codliy.com/license",
    "livePreview" => "https://codliy.com",
    "productPage" => "https://codliy.com",
    "support" => "https://codliy.com/contact",
    "moreThemes" => "https://codliy.com",
    "documentation" => "https://codliy.com/docs",
    "generator" => "",
    "changelog" => "https://codliy.com/changelog",
    "repository" => "https://github.com/codliy",
    "gitRepo" => "codliy",
    "gitRepoAccess" => "codliy",
    "githubFreeUrl" => "https://github.com/codliy",
    "facebookUrl" => "https://www.facebook.com/codliy",
    "twitterUrl" => "https://twitter.com/codliy",
    "githubUrl" => "https://github.com/codliy",
    "dribbbleUrl" => "https://dribbble.com/codliy",
    "instagramUrl" => "https://www.instagram.com/codliy",
    "linkedinUrl" => "https://www.linkedin.com/company/codliy",
];
